<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515182347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE horse_care (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, care_date DATE NOT NULL, notes VARCHAR(255) DEFAULT NULL, type_care_id INT NOT NULL, entered_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33B88F76DA5192B0 ON horse_care (type_care_id)');
        $this->addSql('CREATE INDEX IDX_33B88F76C443EDD ON horse_care (entered_by_id)');
        $this->addSql('CREATE TABLE horse_care_horse (horse_care_id INT NOT NULL, horse_id INT NOT NULL, PRIMARY KEY (horse_care_id, horse_id))');
        $this->addSql('CREATE INDEX IDX_F88437A74F9C6EDB ON horse_care_horse (horse_care_id)');
        $this->addSql('CREATE INDEX IDX_F88437A776B275AD ON horse_care_horse (horse_id)');
        $this->addSql('ALTER TABLE horse_care ADD CONSTRAINT FK_33B88F76DA5192B0 FOREIGN KEY (type_care_id) REFERENCES type_care (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horse_care ADD CONSTRAINT FK_33B88F76C443EDD FOREIGN KEY (entered_by_id) REFERENCES "app_user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horse_care_horse ADD CONSTRAINT FK_F88437A74F9C6EDB FOREIGN KEY (horse_care_id) REFERENCES horse_care (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE horse_care_horse ADD CONSTRAINT FK_F88437A776B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE horse_care DROP CONSTRAINT FK_33B88F76DA5192B0');
        $this->addSql('ALTER TABLE horse_care DROP CONSTRAINT FK_33B88F76C443EDD');
        $this->addSql('ALTER TABLE horse_care_horse DROP CONSTRAINT FK_F88437A74F9C6EDB');
        $this->addSql('ALTER TABLE horse_care_horse DROP CONSTRAINT FK_F88437A776B275AD');
        $this->addSql('DROP TABLE horse_care');
        $this->addSql('DROP TABLE horse_care_horse');
    }
}
