<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512114649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discipline (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, mnemonique VARCHAR(50) DEFAULT \'-\' NOT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, type_equitation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75BEEE3FAE6460B2 ON discipline (type_equitation_id)');
        $this->addSql('ALTER TABLE discipline ADD CONSTRAINT FK_75BEEE3FAE6460B2 FOREIGN KEY (type_equitation_id) REFERENCES type_equitation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE discipline DROP CONSTRAINT FK_75BEEE3FAE6460B2');
        $this->addSql('DROP TABLE discipline');
    }
}
