<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515100015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, phone INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rider_ranch (rider_id INT NOT NULL, ranch_id INT NOT NULL, PRIMARY KEY (rider_id, ranch_id))');
        $this->addSql('CREATE INDEX IDX_B0E864DEFF881F6 ON rider_ranch (rider_id)');
        $this->addSql('CREATE INDEX IDX_B0E864DE2D68AEAC ON rider_ranch (ranch_id)');
        $this->addSql('ALTER TABLE rider_ranch ADD CONSTRAINT FK_B0E864DEFF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_ranch ADD CONSTRAINT FK_B0E864DE2D68AEAC FOREIGN KEY (ranch_id) REFERENCES ranch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE horse ADD ranch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE horse ADD CONSTRAINT FK_629A2F182D68AEAC FOREIGN KEY (ranch_id) REFERENCES ranch (id)');
        $this->addSql('CREATE INDEX IDX_629A2F182D68AEAC ON horse (ranch_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rider_ranch DROP CONSTRAINT FK_B0E864DEFF881F6');
        $this->addSql('ALTER TABLE rider_ranch DROP CONSTRAINT FK_B0E864DE2D68AEAC');
        $this->addSql('DROP TABLE ranch');
        $this->addSql('DROP TABLE rider_ranch');
        $this->addSql('ALTER TABLE horse DROP CONSTRAINT FK_629A2F182D68AEAC');
        $this->addSql('DROP INDEX IDX_629A2F182D68AEAC');
        $this->addSql('ALTER TABLE horse DROP ranch_id');
    }
}
