<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515092725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competition_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, order_number SMALLINT DEFAULT NULL, rank SMALLINT DEFAULT NULL, number_participant SMALLINT DEFAULT NULL, score INT DEFAULT NULL, score_percent INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, start_date DATE DEFAULT NULL, competition_registration_id INT NOT NULL, discipline_id INT NOT NULL, category_id INT NOT NULL, level_id INT DEFAULT NULL, type_test_id INT NOT NULL, dressage_test_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D896AFA6585067E3 ON competition_entry (competition_registration_id)');
        $this->addSql('CREATE INDEX IDX_D896AFA6A5522701 ON competition_entry (discipline_id)');
        $this->addSql('CREATE INDEX IDX_D896AFA612469DE2 ON competition_entry (category_id)');
        $this->addSql('CREATE INDEX IDX_D896AFA65FB14BA7 ON competition_entry (level_id)');
        $this->addSql('CREATE INDEX IDX_D896AFA6367C6BAC ON competition_entry (type_test_id)');
        $this->addSql('CREATE INDEX IDX_D896AFA64827EB35 ON competition_entry (dressage_test_id)');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA6585067E3 FOREIGN KEY (competition_registration_id) REFERENCES competition_registration (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA6A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA65FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA6367C6BAC FOREIGN KEY (type_test_id) REFERENCES type_test (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_entry ADD CONSTRAINT FK_D896AFA64827EB35 FOREIGN KEY (dressage_test_id) REFERENCES dressage_test (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA6585067E3');
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA6A5522701');
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA612469DE2');
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA65FB14BA7');
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA6367C6BAC');
        $this->addSql('ALTER TABLE competition_entry DROP CONSTRAINT FK_D896AFA64827EB35');
        $this->addSql('DROP TABLE competition_entry');
    }
}
