<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512143936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dressage_test (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, mnemonique VARCHAR(50) DEFAULT \'-\' NOT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, discipline_id INT NOT NULL, category_id INT NOT NULL, level_id INT NOT NULL, type_test_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B58DA77DA5522701 ON dressage_test (discipline_id)');
        $this->addSql('CREATE INDEX IDX_B58DA77D12469DE2 ON dressage_test (category_id)');
        $this->addSql('CREATE INDEX IDX_B58DA77D5FB14BA7 ON dressage_test (level_id)');
        $this->addSql('CREATE INDEX IDX_B58DA77D367C6BAC ON dressage_test (type_test_id)');
        $this->addSql('ALTER TABLE dressage_test ADD CONSTRAINT FK_B58DA77DA5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dressage_test ADD CONSTRAINT FK_B58DA77D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dressage_test ADD CONSTRAINT FK_B58DA77D5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dressage_test ADD CONSTRAINT FK_B58DA77D367C6BAC FOREIGN KEY (type_test_id) REFERENCES type_test (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dressage_test DROP CONSTRAINT FK_B58DA77DA5522701');
        $this->addSql('ALTER TABLE dressage_test DROP CONSTRAINT FK_B58DA77D12469DE2');
        $this->addSql('ALTER TABLE dressage_test DROP CONSTRAINT FK_B58DA77D5FB14BA7');
        $this->addSql('ALTER TABLE dressage_test DROP CONSTRAINT FK_B58DA77D367C6BAC');
        $this->addSql('DROP TABLE dressage_test');
    }
}
