<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515094122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE protocol_figure_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, final_score INT DEFAULT NULL, protocol_id INT NOT NULL, protocol_figure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E6FD8DD1CCD59258 ON protocol_figure_score (protocol_id)');
        $this->addSql('CREATE INDEX IDX_E6FD8DD1E7DEF2D4 ON protocol_figure_score (protocol_figure_id)');
        $this->addSql('ALTER TABLE protocol_figure_score ADD CONSTRAINT FK_E6FD8DD1CCD59258 FOREIGN KEY (protocol_id) REFERENCES protocol (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE protocol_figure_score ADD CONSTRAINT FK_E6FD8DD1E7DEF2D4 FOREIGN KEY (protocol_figure_id) REFERENCES protocol_figure (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE protocol_figure_score DROP CONSTRAINT FK_E6FD8DD1CCD59258');
        $this->addSql('ALTER TABLE protocol_figure_score DROP CONSTRAINT FK_E6FD8DD1E7DEF2D4');
        $this->addSql('DROP TABLE protocol_figure_score');
    }
}
