<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514161112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE type_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, mnemonique VARCHAR(50) DEFAULT \'-\' NOT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, type_equitation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67FE9493AE6460B2 ON type_equipment (type_equitation_id)');
        $this->addSql('ALTER TABLE type_equipment ADD CONSTRAINT FK_67FE9493AE6460B2 FOREIGN KEY (type_equitation_id) REFERENCES type_equitation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE type_equipment DROP CONSTRAINT FK_67FE9493AE6460B2');
        $this->addSql('DROP TABLE type_equipment');
    }
}
