<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506154340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE galop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rider_galop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, obtained_year INT DEFAULT NULL, rider_id INT NOT NULL, galop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4B57F18FF881F6 ON rider_galop (rider_id)');
        $this->addSql('CREATE INDEX IDX_A4B57F184A6A299 ON rider_galop (galop_id)');
        $this->addSql('ALTER TABLE rider_galop ADD CONSTRAINT FK_A4B57F18FF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rider_galop ADD CONSTRAINT FK_A4B57F184A6A299 FOREIGN KEY (galop_id) REFERENCES galop (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rider_galop DROP CONSTRAINT FK_A4B57F18FF881F6');
        $this->addSql('ALTER TABLE rider_galop DROP CONSTRAINT FK_A4B57F184A6A299');
        $this->addSql('DROP TABLE galop');
        $this->addSql('DROP TABLE rider_galop');
    }
}
