<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515192417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment_discipline (equipment_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (equipment_id, discipline_id))');
        $this->addSql('CREATE INDEX IDX_5CB51AE1517FE9FE ON equipment_discipline (equipment_id)');
        $this->addSql('CREATE INDEX IDX_5CB51AE1A5522701 ON equipment_discipline (discipline_id)');
        $this->addSql('CREATE TABLE reminder_maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expected_date DATE NOT NULL, interval_personnal_value INT DEFAULT NULL, interval_personnal_unit VARCHAR(20) DEFAULT NULL, equipment_id INT DEFAULT NULL, type_maintenance_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50578A88517FE9FE ON reminder_maintenance (equipment_id)');
        $this->addSql('CREATE INDEX IDX_50578A88A0012B28 ON reminder_maintenance (type_maintenance_id)');
        $this->addSql('ALTER TABLE equipment_discipline ADD CONSTRAINT FK_5CB51AE1517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE equipment_discipline ADD CONSTRAINT FK_5CB51AE1A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reminder_maintenance ADD CONSTRAINT FK_50578A88517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id)');
        $this->addSql('ALTER TABLE reminder_maintenance ADD CONSTRAINT FK_50578A88A0012B28 FOREIGN KEY (type_maintenance_id) REFERENCES type_maintenance (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment_discipline DROP CONSTRAINT FK_5CB51AE1517FE9FE');
        $this->addSql('ALTER TABLE equipment_discipline DROP CONSTRAINT FK_5CB51AE1A5522701');
        $this->addSql('ALTER TABLE reminder_maintenance DROP CONSTRAINT FK_50578A88517FE9FE');
        $this->addSql('ALTER TABLE reminder_maintenance DROP CONSTRAINT FK_50578A88A0012B28');
        $this->addSql('DROP TABLE equipment_discipline');
        $this->addSql('DROP TABLE reminder_maintenance');
    }
}
