<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514115440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE protocol_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre SMALLINT NOT NULL, marker VARCHAR(100) DEFAULT NULL, description TEXT NOT NULL, graph_data JSON DEFAULT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, protocol_figure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5244E03EE7DEF2D4 ON protocol_movement (protocol_figure_id)');
        $this->addSql('ALTER TABLE protocol_movement ADD CONSTRAINT FK_5244E03EE7DEF2D4 FOREIGN KEY (protocol_figure_id) REFERENCES protocol_figure (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE protocol_movement DROP CONSTRAINT FK_5244E03EE7DEF2D4');
        $this->addSql('DROP TABLE protocol_movement');
    }
}
