<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515184426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reminder_care (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expected_date DATE NOT NULL, interval_personnal_value INT DEFAULT NULL, interval_personnal_unit VARCHAR(20) DEFAULT NULL, horse_id INT NOT NULL, type_care_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76EF746C76B275AD ON reminder_care (horse_id)');
        $this->addSql('CREATE INDEX IDX_76EF746CDA5192B0 ON reminder_care (type_care_id)');
        $this->addSql('ALTER TABLE reminder_care ADD CONSTRAINT FK_76EF746C76B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reminder_care ADD CONSTRAINT FK_76EF746CDA5192B0 FOREIGN KEY (type_care_id) REFERENCES type_care (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reminder_care DROP CONSTRAINT FK_76EF746C76B275AD');
        $this->addSql('ALTER TABLE reminder_care DROP CONSTRAINT FK_76EF746CDA5192B0');
        $this->addSql('DROP TABLE reminder_care');
    }
}
