<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260508192126 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE horse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, affix VARCHAR(255) DEFAULT NULL, birth_date DATE DEFAULT NULL, sire VARCHAR(20) DEFAULT NULL, breed_id INT NOT NULL, coat_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_629A2F18A8B4A30F ON horse (breed_id)');
        $this->addSql('CREATE INDEX IDX_629A2F1879F419D ON horse (coat_id)');
        $this->addSql('CREATE INDEX IDX_629A2F187E3C61F9 ON horse (owner_id)');
        $this->addSql('CREATE TABLE horse_rider (horse_id INT NOT NULL, rider_id INT NOT NULL, PRIMARY KEY (horse_id, rider_id))');
        $this->addSql('CREATE INDEX IDX_55C3DA0476B275AD ON horse_rider (horse_id)');
        $this->addSql('CREATE INDEX IDX_55C3DA04FF881F6 ON horse_rider (rider_id)');
        $this->addSql('ALTER TABLE horse ADD CONSTRAINT FK_629A2F18A8B4A30F FOREIGN KEY (breed_id) REFERENCES breed (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horse ADD CONSTRAINT FK_629A2F1879F419D FOREIGN KEY (coat_id) REFERENCES coat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horse ADD CONSTRAINT FK_629A2F187E3C61F9 FOREIGN KEY (owner_id) REFERENCES "app_user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horse_rider ADD CONSTRAINT FK_55C3DA0476B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE horse_rider ADD CONSTRAINT FK_55C3DA04FF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE horse DROP CONSTRAINT FK_629A2F18A8B4A30F');
        $this->addSql('ALTER TABLE horse DROP CONSTRAINT FK_629A2F1879F419D');
        $this->addSql('ALTER TABLE horse DROP CONSTRAINT FK_629A2F187E3C61F9');
        $this->addSql('ALTER TABLE horse_rider DROP CONSTRAINT FK_55C3DA0476B275AD');
        $this->addSql('ALTER TABLE horse_rider DROP CONSTRAINT FK_55C3DA04FF881F6');
        $this->addSql('DROP TABLE horse');
        $this->addSql('DROP TABLE horse_rider');
    }
}
