<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512130103 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, mnemonique VARCHAR(50) DEFAULT \'-\' NOT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9AEACC1312469DE2 ON level (category_id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC1312469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC1312469DE2');
        $this->addSql('DROP TABLE level');
    }
}
