<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515093552 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE protocol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, raw_text TEXT NOT NULL, total_points INT DEFAULT NULL, max_points INT NOT NULL, percentage INT DEFAULT NULL, general_comment VARCHAR(255) DEFAULT NULL, competition_entry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8C0BC4C8B47726D ON protocol (competition_entry_id)');
        $this->addSql('ALTER TABLE protocol ADD CONSTRAINT FK_C8C0BC4C8B47726D FOREIGN KEY (competition_entry_id) REFERENCES competition_entry (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE protocol DROP CONSTRAINT FK_C8C0BC4C8B47726D');
        $this->addSql('DROP TABLE protocol');
    }
}
