<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515091008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competition_registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, registration_date DATE NOT NULL, bib_number INT DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, competition_id INT NOT NULL, horse_id INT NOT NULL, rider_id INT NOT NULL, status_registration_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D53D5A337B39D312 ON competition_registration (competition_id)');
        $this->addSql('CREATE INDEX IDX_D53D5A3376B275AD ON competition_registration (horse_id)');
        $this->addSql('CREATE INDEX IDX_D53D5A33FF881F6 ON competition_registration (rider_id)');
        $this->addSql('CREATE INDEX IDX_D53D5A339367BDB6 ON competition_registration (status_registration_id)');
        $this->addSql('ALTER TABLE competition_registration ADD CONSTRAINT FK_D53D5A337B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_registration ADD CONSTRAINT FK_D53D5A3376B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_registration ADD CONSTRAINT FK_D53D5A33FF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition_registration ADD CONSTRAINT FK_D53D5A339367BDB6 FOREIGN KEY (status_registration_id) REFERENCES status_competition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competition_registration DROP CONSTRAINT FK_D53D5A337B39D312');
        $this->addSql('ALTER TABLE competition_registration DROP CONSTRAINT FK_D53D5A3376B275AD');
        $this->addSql('ALTER TABLE competition_registration DROP CONSTRAINT FK_D53D5A33FF881F6');
        $this->addSql('ALTER TABLE competition_registration DROP CONSTRAINT FK_D53D5A339367BDB6');
        $this->addSql('DROP TABLE competition_registration');
    }
}
