<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515100854 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pension (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_date DATE NOT NULL, end_date DATE DEFAULT NULL, ranch_id INT NOT NULL, horse_id INT NOT NULL, type_pension_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79DC9C7A2D68AEAC ON pension (ranch_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_79DC9C7A76B275AD ON pension (horse_id)');
        $this->addSql('CREATE INDEX IDX_79DC9C7A70B5A503 ON pension (type_pension_id)');
        $this->addSql('CREATE TABLE type_pension (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, mnemonique VARCHAR(50) DEFAULT \'-\' NOT NULL, est_actif BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE pension ADD CONSTRAINT FK_79DC9C7A2D68AEAC FOREIGN KEY (ranch_id) REFERENCES ranch (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pension ADD CONSTRAINT FK_79DC9C7A76B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pension ADD CONSTRAINT FK_79DC9C7A70B5A503 FOREIGN KEY (type_pension_id) REFERENCES type_pension (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pension DROP CONSTRAINT FK_79DC9C7A2D68AEAC');
        $this->addSql('ALTER TABLE pension DROP CONSTRAINT FK_79DC9C7A76B275AD');
        $this->addSql('ALTER TABLE pension DROP CONSTRAINT FK_79DC9C7A70B5A503');
        $this->addSql('DROP TABLE pension');
        $this->addSql('DROP TABLE type_pension');
    }
}
