<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515090021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, status_competition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B50A2CB1FB717C88 ON competition (status_competition_id)');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_B50A2CB1FB717C88 FOREIGN KEY (status_competition_id) REFERENCES status_competition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE competition DROP CONSTRAINT FK_B50A2CB1FB717C88');
        $this->addSql('DROP TABLE competition');
    }
}
