<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260815182700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usage_date DATE NOT NULL, call_count INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ai_usage_day ON ai_usage (usage_date)');
        $this->addSql('ALTER TABLE competition_entry ALTER score_percent TYPE NUMERIC(6, 3)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE ai_usage');
        $this->addSql('ALTER TABLE competition_entry ALTER score_percent TYPE INT');
    }
}
