<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512161200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE protocol_figure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number SMALLINT NOT NULL, directive_ideas TEXT DEFAULT NULL, coefficient NUMERIC(4, 2) NOT NULL, technical_note TEXT DEFAULT NULL, est_actif BOOLEAN NOT NULL, dressage_test_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_622BB6C84827EB35 ON protocol_figure (dressage_test_id)');
        $this->addSql('ALTER TABLE protocol_figure ADD CONSTRAINT FK_622BB6C84827EB35 FOREIGN KEY (dressage_test_id) REFERENCES dressage_test (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE protocol_step DROP CONSTRAINT fk_46b7014b4827eb35');
        $this->addSql('DROP TABLE protocol_step');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE protocol_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre INT NOT NULL, marker VARCHAR(100) DEFAULT NULL, description TEXT NOT NULL, coefficient NUMERIC(4, 2) DEFAULT NULL, technical_note TEXT DEFAULT NULL, graph_data JSON DEFAULT NULL, est_actif BOOLEAN NOT NULL, dressage_test_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_46b7014b4827eb35 ON protocol_step (dressage_test_id)');
        $this->addSql('ALTER TABLE protocol_step ADD CONSTRAINT fk_46b7014b4827eb35 FOREIGN KEY (dressage_test_id) REFERENCES dressage_test (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE protocol_figure DROP CONSTRAINT FK_622BB6C84827EB35');
        $this->addSql('DROP TABLE protocol_figure');
    }
}
