<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515191850 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, brand VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, purchase_date DATE DEFAULT NULL, rider_id INT DEFAULT NULL, type_equipment_id INT DEFAULT NULL, type_saddle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D338D583FF881F6 ON equipment (rider_id)');
        $this->addSql('CREATE INDEX IDX_D338D583D63C53FB ON equipment (type_equipment_id)');
        $this->addSql('CREATE INDEX IDX_D338D583A206AE6E ON equipment (type_saddle_id)');
        $this->addSql('CREATE TABLE equipment_maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, maintenance_date DATE NOT NULL, notes VARCHAR(255) DEFAULT NULL, type_maintenance_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EC60CCEA0012B28 ON equipment_maintenance (type_maintenance_id)');
        $this->addSql('CREATE TABLE equipment_maintenance_equipment (equipment_maintenance_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY (equipment_maintenance_id, equipment_id))');
        $this->addSql('CREATE INDEX IDX_B61BF90C23C256BD ON equipment_maintenance_equipment (equipment_maintenance_id)');
        $this->addSql('CREATE INDEX IDX_B61BF90C517FE9FE ON equipment_maintenance_equipment (equipment_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583FF881F6 FOREIGN KEY (rider_id) REFERENCES rider (id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583D63C53FB FOREIGN KEY (type_equipment_id) REFERENCES type_equipment (id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583A206AE6E FOREIGN KEY (type_saddle_id) REFERENCES type_saddle (id)');
        $this->addSql('ALTER TABLE equipment_maintenance ADD CONSTRAINT FK_4EC60CCEA0012B28 FOREIGN KEY (type_maintenance_id) REFERENCES type_maintenance (id)');
        $this->addSql('ALTER TABLE equipment_maintenance_equipment ADD CONSTRAINT FK_B61BF90C23C256BD FOREIGN KEY (equipment_maintenance_id) REFERENCES equipment_maintenance (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE equipment_maintenance_equipment ADD CONSTRAINT FK_B61BF90C517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583FF881F6');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583D63C53FB');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583A206AE6E');
        $this->addSql('ALTER TABLE equipment_maintenance DROP CONSTRAINT FK_4EC60CCEA0012B28');
        $this->addSql('ALTER TABLE equipment_maintenance_equipment DROP CONSTRAINT FK_B61BF90C23C256BD');
        $this->addSql('ALTER TABLE equipment_maintenance_equipment DROP CONSTRAINT FK_B61BF90C517FE9FE');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipment_maintenance');
        $this->addSql('DROP TABLE equipment_maintenance_equipment');
    }
}
